### ISSUE TITLE
Respect video track transforms.

### ISSUE THREAD

**Issue by vade** [Synopsis/Synopsis-Analyzer#25]
Holy fuck Anton, its just rectangles™

**Comment by vade** [comment]
Also - this is important.

For analysis modules that contain position data, should the coordinates be relative to the uncorrected 'raster', or to what the rotated presentation frame expects?

IE: A face in the top left, but shot on a iPhone that was held 90º off angle. 

Ponder this.

**Comment by brianchasalow** [comment]
probably rotated to what the presentation frame expects, i would think. it's the video track transform, not the videotrackandmetadataandeveryothertrack transform.

**Comment by vade** [comment]
Well, I'm not going to pre-rotate the pixel buffers, but I'm going to pass in the transform and rotate the coordinates to match what the transform expects the media to be presented at. Does that make sense?

**Comment by vade** [comment]
Im already respecting the track transforms, just not doing metadata transforms along-side, fyi.

**Comment by vade** [comment]
Also - doing pass through means you cant rotate the pixel buffers since you're just shitting out sample buffers into a new container in DTS order - so you cant re-align them or you're forced to re-encode.

So its gotta be a transform on the metadata :X

**Comment by brianchasalow** [comment]
I think we're saying the same thing, but to be sure I understand, here's an example: iPhone video was shot in LandscapeLeft mode. iOS for whatever reason might encode video as portrait, but adds a flag saying 'rotate this sucker 90 degrees'.

When you do the analysis, you can do whatever you want, presumably, because this stage is expected to be 'offline' and take awhile to process. (Maybe that's the part that's not always true in your case, though?)

During analysis, can't you detect that video track transform, rotate the Portrait pixel buffer to be LandscapeLeft, and perform analysis on that? So, the _rendered_ metadata track is effectively 'LandscapeLeft' while the video track is 'on-disk-as-portrait with shouldBeShownAsLandscapeLeft flag' ?

**Comment by vade** [comment]
Sure - but the issue with rotating a pixel buffer is its slow and analysis is already slow. My preference is to pass in the track transform and use that as a 'free' matrix multiply to rotate the coordinates for any points etc that require it. 

But yea, thats exactly the end goal :+1:

**Comment by brianchasalow** [comment]
grumble.

**Comment by vade** [comment]
Why.

**Comment by brianchasalow** [comment]
wait, so you're going to do that multiply on the rendered metadata before you write to json, or you're going to supply the metadata transform?

**Comment by brianchasalow** [comment]
this stuff is annoyingly hard to discuss in the abstract!

**Comment by vade** [comment]
Haha. I hear you. "I'm" going to do the transform on the metadata so when clients read it out, its in the 'expected video presentation' coordinate system

The Metadata API for folks (like you) who implement analysis plugins will get the transform from the video track passed in so they can handle that transform should the data they return be a coordinate.

Im in he process of updating the metadata code to apply the transform. Right now, I take it in, but don't do anything with it :)

**Comment by brianchasalow** [comment]
Right. cool. we're saying the same thing. :banana:

**Comment by vade** [comment]
banana for scale.

**Comment by vade** [comment]
Im reneging my previous thought about having plugin authors respect the metadata track transform. I think if this is going to be cross platform plugins at some point I need to pass in a base address , width, height, stride shit, so anyone can format the bytes for their platform and not deal with platform specific idiocy like CMSampleBuffers or CVPixelBuffers.

That allows the host app to do a - if requested - downsample pass for speed, - which at that point you might as well just orient the fucking buffer to the output raster.

:banana:

**Comment by brianchasalow** [comment]
you do you, pal
