### ISSUE TITLE
[Bug Report] PIxel Aspect Ratio not being respected in our Hap Player Layer

### ISSUE THREAD

**Issue by vade** [Synopsis/Synopsis-Analyzer#57]
Preview a movie with a non square pixel aspect ratio like an HDV stream.

The preview is compressed as if its a 1:1 pixel aspect ratio.

**Comment by mrRay** [comment]
this has been addressed in the 'development' branch, primarily in commit 71b825f547e8c3a1690ca01979a3b94fe749275c
