### ISSUE TITLE
[Bug Report] Improve error messages for end users

### ISSUE THREAD

**Issue by vade** [Synopsis/Synopsis-Analyzer#61]
**Describe the bug**
`There was a problem installing the CLI (couldn't make the new symlink- You don't have permission to save the file "synopsis-enc" in the folder "bin".)`

This isn't super clear if you dont know what a CLI is.

Also, we should deduce the issue (likely lacking admin privs im guessing)

**Expected behavior**
`There was a problem installing the command line tools. Please try with an administrators account.

Error: "couldn't make a new symlink- You don't have permission to save the file "synopsis-enc" in the folder "actual path /bin".)'

Additionally we could prompt for an admin password but that does require some additional setup that IIRC is a pain in the ass to set up a privilege helper tool for installation.

**Comment by mrRay** [comment]
installing the CLI on launch seems like it's kind of cumbersome in general- you launch the app and the first thing you see is a modal alert about how it was installed.  what if CLI installation was made into a menu option, too?

**Comment by dlublin** [comment]
Agreed with @mrRay; a menu option like "install command line tools" is how BBEdit handles this. 

Once that was implemented, like other apps we could offer a first / second time launch prompt that asks "would you like to install the command line tools?" and if the user declines they can choose to do so later via the menu.

**Comment by vade** [comment]
100% agree -  thats the best path forward!

**Comment by mrRay** [comment]
ae8965692c4a6d38d8d0d88e360ba03ed17745df moves CLI installation into the app menu.  it doesn't, however, change the contents of the error messages, which are already copied directly from the NSError's localized description ("you don't have permission" literally means "you don't have permission").  would i be correct in presuming that if the user explicitly chooses to install the command-line tools that these error messages are sufficiently descriptive?

**Comment by vade** [comment]
The issue isn't the 'dont have permissions' - its the `There was a problem installing the CLI` (end users might not understand CLI means terminal command line interface).

I think we can do 
`There was a problem installing the terminal command for synopsis-enc  (couldn't make the new symlink- You don't have permission to save the file "synopsis-enc" in the folder "bin".)`

or something along those lines.

**Comment by mrRay** [comment]
7ee367aa87c410a40def2138937a332895abd4ed
