### ISSUE TITLE
Optionally throttle CPU usage

### ISSUE THREAD

**Issue by damian0815** [Synopsis/Synopsis-Analyzer#63]
It should be possible to optionally throttle back CPU usage so that transcoding can run in the background without bringing the rest of the system to a halt. (To be clear this should be an explicit user action)

**Comment by vade** [comment]
Totally. I have prefs set up for this, but have yet to hook it up. 

One nuance is lack of control of 3rd party libs like OpenCV / TF where we cant explicitly control (to my knowledge) how many threads are spooled or what ops are parallelized). I had in mind a mechanism for reducing the number of operations the transcode and analysis ops could run in parallel as a first level, as well as pass in some keys to optionally not tile Accelerate framework, etc.

**Comment by vade** [comment]
b00538b79ed9567b3675802a736a35a96f7b03b3 has fixes for what we can control
