### ISSUE TITLE
UI : Passthrough Preset Category not selectable in default preset dropdown

### ISSUE THREAD

**Issue by archo-p** [Synopsis/Synopsis-Analyzer#76]
After you de-select the passthrough option in the Default Presets list dropdown you can no longer access it in the same list.

I am seeing this in Analyzer 1.0a2

**Comment by vade** [comment]
Oh. Indeed. Thank you. Can reproduce.

**Comment by vade** [comment]
Thanks. wasn't paying attention and missed this. Ive resolved this in the source tree. I'll roll this into the next alpha. Can you hang until this is resolved?

**Comment by archo-p** [comment]
Yes totally fine to wait, just making it known!  Cheers

**Comment by vade** [comment]
Thank you!
