### ISSUE TITLE
Allow adding folder to analysis queue

### ISSUE THREAD

**Issue by skyebook** [Synopsis/Synopsis-Analyzer#78]
The open dialogue that lets you add media only supports selecting single items (which are files). Would be great to be able to select a folder and have it walk the directory structure and find compatible movies 😃

**Comment by vade** [comment]
You can drag in a selection of files from the finder into the main UI window as a drag destination in the mean time - is that helpful?

**Comment by skyebook** [comment]
much thanks, such helpful!

**Comment by vade** [comment]
I definitely want to have a 'transcode entire folder hierarchy' at some point, so it copies the sub-tree layout and puts things in their respective destinations, like so:

source/
source/folder 1/1.mov
source/folder 1/2.mov
source/folder 1/3.mov
source/folder 2/1.mov
source/folder 2/2.mov

destination_analyzed/
destination_analyzed/folder 1/1.mov
destination_analyzed/folder 1/2.mov
destination_analyzed/folder 1/3.mov
destination_analyzed/folder 2/1.mov
destination_analyzed/folder 2/2.mov

But I think I need to do a lot of work on the main UI elements so you can load up stuff, configure custom settings and manually start transcodes 'batches'.

**Comment by vade** [comment]
This is mostly done in the automation work, but I dont have an updated UI to reflect the changes yet.

**Comment by vade** [comment]
Can now drag in folders to the UI. Should work regardless of pref setting.
