### ISSUE TITLE
JSON Export RFE :: option to output only the global data

### ISSUE THREAD

**Issue by archo-p** [Synopsis/Synopsis-Analyzer#79]
It's not hard to fetch the global data out of the full exported JSON, but an option to export only the global bit of data would be nice to save on  disk space, since the full uncompressed metadata frames list ends up being a pretty hefty JSON file for long vids!

**Comment by vade** [comment]
Im assuming an option in the prefs next to export JSON with something like "All data" or Global (something like a menu or a radio which has exclusive selection) will suffice?

**Comment by archo-p** [comment]
Yeah, perhaps just two check boxes, one for the whole thing, and one for the global...  so you could potentially get both in one go if desired...

**Comment by vade** [comment]
Added typedef enum : NSInteger {
    // Dont write out any JSON
    SynopsisMetadataEncoderJSONOptionNone = 0,
    // Single sidecar file
    SynopsisMetadataEncoderJSONOptionContiguous = 1,
    // Global metadata only sidecar file (no per frame)
    SynopsisMetadataEncoderJSONOptionGlobalOnly = 2,
    // GLobal metadata as well as individial per frame sequences
    SynopsisMetadataEncoderJSONOptionSequence = 3,
    // Export training data used to make new dictionary files for ZSTD
    SynopsisMetadataEncoderJSONOptionZSTDTraining = -1,

} SynopsisMetadataEncoderJSONOption;

in ZSTD metadata refactor branch
